Made `label` optional in the parse strategy
EMMC-ASBL/oteapi-dlite pull request #252
Opened 2024-06-24 13:21 UTC by jesper-friis

# Description:
Made label optional in the parse strategy. Added unused metadata field.

## Type of change:
- [ ] Bug fix.
- [ ] New feature.
- [x] Documentation update.

## Checklist for the reviewer:

This checklist should be used as a help for the reviewer.

- [ ] Is the change limited to one issue?
- [ ] Does this PR close the issue?
- [ ] Is the code easy to read and understand, including clearly named variables?
- [ ] Do all new feature have an accompanying new test?
- [ ] Has the documentation been updated as necessary?

2024-06-24 13:22 UTC, francescalb commented on oteapi_dlite/strategies/parse.py
> +                "the strategy, but for a documentation point of view this is "
```suggestion
                "the DLite driver (DLite plugin), but for a documentation point of view this is "
```

2024-06-24 14:33 UTC, francescalb commented on oteapi_dlite/strategies/parse.py
> +                "a very important field."
```suggestion
                "the DLite driver (DLite plugin), but for a documentation "
                "point of view this is a very important field."
```

2024-06-24 14:41 UTC, francescalb approved these changes

2024-06-25 06:52 UTC, francescalb requested changes
I orignially approved, but it does not work. I have added a fix.

However, there was not test for this core strategy, and this is something to be remedied immediately. I have started on a test, but please complete it.

2024-06-25 10:32 UTC, jesper-friis commented on tests/entities/Molecule.yaml
> +da31ff66-98af-590c-855d-386c63617755:
Can be removed - the generic yaml serialisation don't have this double-nesting.

2024-06-25 12:45 UTC, francescalb approved these changes
good

2024-06-25 12:45 UTC, merged